apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cyi90tj0s-python 
  janus-idp.io/tekton: cyi90tj0s-python
  backstage.io/kubernetes-id: cyi90tj0s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cyi90tj0s-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  